### ISSUE TITLE
Creare server vuoto

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/conto-corrente-bancario-s#1]

**Comment by capponiFelice92** [comment]
risolto commit 023443a2bcbe9460dad22950b23c2d0b1b7232a4

**Comment by capponiFelice92** [comment]
creiamo anche, controller, service, serviceImpl, vuoti?
creiamo anche entities e repository?

**Comment by luca-lezzerini** [comment]
Sí

**Comment by luca-lezzerini** [comment]
Le entities e i repository no

**Comment by capponiFelice92** [comment]
controller, service, serviceImpl vuoti disponibili con il commit 61c3caf

**Comment by capponiFelice92** [comment]
prof potrebbe chiudere questo ticket?
