### ISSUE TITLE
UC Associa CD

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/conto-corrente-bancario-s#10]

**Comment by capponiFelice92** [comment]
0c23975c170421d1570a4b4b89fef29e2c413f05

**Comment by capponiFelice92** [comment]
completato al commit 5744018ee7b5a2fe1f3eab55b5b1fe28af43c63e

**Comment by capponiFelice92** [comment]
risolto bug associazione a C/D senza che l'utente ne abbia selezionato prima uno
