### ISSUE TITLE
UC E/C CD

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/conto-corrente-bancario-s#20]

**Comment by capponiFelice92** [comment]
iniziato 7ff82c93a57bc78b2d9041915aeb6d7f2fc5c673

**Comment by capponiFelice92** [comment]
ce22539f177e6c9fe762f7e080575e1b9c931594
E' ora possibile trovare tutti i conti deposito associati al cliente, manca ancora la query per ricerca Conti corrente e Conti prestito associati

**Comment by daniele-bit** [comment]
4fd458c0079f61dd903bc93ba15076a44ecd0753

**Comment by daniele-bit** [comment]
Ripristinato controller  Demo 4fd458c0079f61dd903bc93ba15076a44ecd0753

**Comment by capponiFelice92** [comment]
4b33529ebea8a3e0d359cad61a7582367f9d89d7

**Comment by daniele-bit** [comment]
a71b435e187c09557b15a8ef8f6d0302863e853e

**Comment by capponiFelice92** [comment]
f3f35203561346969ffc4e67a5ad491d77602efc
