### ISSUE TITLE
Definire foglio globale di stile (tema)

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/conto-corrente-bancario-s#26]
Creare un foglio di stile CSS globale nel client (dentro app) chiamato theme.css.
Definire a piacere gli stili per:

titolo-grande
etichetta-testo
etichetta-bottone
bottone-attivo
bottone-disabilitato
campo-input
body
tabella
header-tabella
riga-tabella

**Comment by ValeriaCom** [comment]
Professore come si imposta un foglio di stile in modo da renderlo globale?

**Comment by luca-lezzerini** [comment]
Citatelo nei fogli di stile del componente, dentro ai parametri del decoratore @Component, l'ultimo parametro è un array di css

**Comment by luca-lezzerini** [comment]
Comunque, se volete una risposta da me, dovete assegnarmi il ticket. Questo l'ho visto solo per caso

**Comment by leoIapp** [comment]
abbiamo implementato il css nel component home-page, ma aspettiamo lei per renderlo globale 
Link:  https://meet.google.com/dbd-kzrg-dyo
