### ISSUE TITLE
Creare home page

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/conto-corrente-bancario-s#27]
Creare home page con pulsanti per i vari casi d'uso (un pulsante per ogni UC)

**Comment by ManuelBava** [comment]
risolto al commit 756aa86bcf1a57b10c043cff230450266bfc0ea2

**Comment by FedericoRez** [comment]
Per la home-page, dobbiamo creare i vari component noi, oppure aspettiamo il lavoro degli altri?
Perche altrimenti non possiamo andare avanti ...

**Comment by luca-lezzerini** [comment]
Per la home page vi servono solo le rotte. Create le rotte e gli altri le useranno. Sentite il responsabile della configurazione per modificare le rotte

**Comment by luca-lezzerini** [comment]
Novità???!!!

**Comment by FedericoRez** [comment]
si prof, per le rotte bisogna creare component nuovi ...
Quelli che dovranno usare le rotte useranno i component usati da noi, giusto?

**Comment by ValeriaCom** [comment]
stiamo provvedendo ora io e Iappelli

**Comment by ValeriaCom** [comment]
risolto al commit e66ec5fc79761b1f7fcb3a754697ae6383a5467c
