### ISSUE TITLE
Sub UC gestione clienti -> aggiungi

### ISSUE THREAD

**Issue by capponiFelice92** [luca-lezzerini/conto-corrente-bancario-s#29]

**Comment by nicoloabatecola** [comment]
Risolto parte Client al commit d6301373c2abc3f4c2c31fb5da7f87a5a6c2d8ca

**Comment by matteo2025** [comment]
Risolto caso d'uso inserimento clienti parte Server. 
Commit: efb2963e81ad2d5dcc7c7659c8af023ea3b625f4

**Comment by nicoloabatecola** [comment]
Aggiunto nuovo componente per il alto client e risolto al commit 79b3b91ad57be3e5885065ea21d29cb24dc1f335

**Comment by nicoloabatecola** [comment]
Piccolo aggiornamento al commit 98d907a75c65036d647b594811a6e7edc47d6e4a

**Comment by matteo2025** [comment]
risolto commit c62e1ff55a3e5229d4e89de1bb1575f9df67a30b
