### ISSUE TITLE
Incoerenza tra diagramma classi nello specifico entità Cliente

### ISSUE THREAD

**Issue by capponiFelice92** [luca-lezzerini/conto-corrente-bancario-s#33]
Nel diagramma delle classi l'entità cliente non possiede data di nascita tra le proprietà, ma alla 1.1.13 delle specifiche del UC gestione cliente è indicato di gestirne anche la data di nascita.
![Conto Corrente Bancario pdf - Personale - Microsoft​ Edge 11_03_2021 18_41_13](https://user-images.githubusercontent.com/78529321/110830323-61f53880-8299-11eb-8a18-573b5106bef9.png)

![Conto Corrente Bancario pdf - Personale - Microsoft​ Edge 11_03_2021 18_40_44](https://user-images.githubusercontent.com/78529321/110830276-53a71c80-8299-11eb-9f55-2968e1820a6c.png)

**Comment by luca-lezzerini** [comment]
Ok, provvedo

**Comment by luca-lezzerini** [comment]
Intanto implementate pure con la data di nascita poi aggiorno il diagramma delle classi

**Comment by luca-lezzerini** [comment]
Risolto al commit 7f572785b5fe570a2bdf1ad31a244ca0509a8ae0
