### ISSUE TITLE
Non è chiaro come deve presentarsi la home page

### ISSUE THREAD

**Issue by ManuelBava** [luca-lezzerini/conto-corrente-bancario-s#36]

**Comment by luca-lezzerini** [comment]
La pagina è una pagina che sopra tanti bottoni quanti sono i casi d'uso l'etichetta del bottone è il nome del caso d'uso e cliccando sul bottone si va sulla pagina che corrisponde a quel caso d'uso

**Comment by ValeriaCom** [comment]
va bene
