### ISSUE TITLE
implementare sub UC cancellazione -> gestione-clienti

### ISSUE THREAD

**Issue by capponiFelice92** [luca-lezzerini/conto-corrente-bancario-s#37]

**Comment by matteo2025** [comment]
implementata cancellazione lato client al commit: b49a64533866940a0a0187651fe542002d4fe3a5

**Comment by nicoloabatecola** [comment]
implementato lato server. Testato e funzionante al commit 7808ac8a510c1eac9d20dc38a3aec4fe911acf2a
