### ISSUE TITLE
UC Gestione CC

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/conto-corrente-bancario-s#4]

**Comment by MatteoPalombo99** [comment]
Creata prima versione al commit 57ff9c0490db036ab5d215ba51a9e2b7c01dbea6

**Comment by MatteoPalombo99** [comment]
Una volta che, implementato associa-cc,  cliente e conto sono associati, occorre che modifichiamo il metodo elimina di gestione-cc in modo che elimini l'elemento simmetricamente?

```
 public ListaContiCorrenteDto eliminaCc(ContoCorrente cc) {
        contoCorrenteRepository.delete(cc);
        List<ContoCorrente> lista = contoCorrenteRepository.findAll();
        return new ListaContiCorrenteDto(lista);
    }
```

**Comment by luca-lezzerini** [comment]
No, il cliente non deve essere rimosso, solo la relazione tra CC e Cliente
