### ISSUE TITLE
Dubbi nella gestione dei serviceImpl

### ISSUE THREAD

**Issue by marcobonaccorso** [luca-lezzerini/conto-corrente-bancario-s#42]
i service impl sono 4, come distribuisco le entità? Ho messo tutti gli oggetti per i test nell'accountManagementServiceImpl, ma immagino vadano distribuite in tutti e 4...ma che ci devo creare  nel ConteCorrenteServiceImpl, nel CustomerManagementServiceImpl e MovimentiManagementServiceImpl?

**Comment by luca-lezzerini** [comment]
I gruppi dei service e dei controller sono nel diagramma seguente:
![image](https://user-images.githubusercontent.com/47611629/110920004-29973e00-831d-11eb-825d-62e5b9f7ca72.png)

- non esiste alcun ContoCorrenteServiceImpl
- nei vari service / impl vanno messi i servizi chiamati dai rispettivi controller e i relativi metodi privati utilizzati

**Comment by luca-lezzerini** [comment]
Potreste chiudere questo ticket?!
