### ISSUE TITLE
Creazione Dto lato client

### ISSUE THREAD

**Issue by MatteoPalombo99** [luca-lezzerini/conto-corrente-bancario-s#43]
I dto lato client vanno creati nel component in cui vanno usati o creati generalmente?

**Comment by luca-lezzerini** [comment]
Non capisco cosa significhi la domanda

**Comment by MatteoPalombo99** [comment]
Dobbiamo creare i dto per trasportare il numero del conto corrente e per ricevere la lista dei numeri dei conti correnti da mettere in tabella.
Ci chiedevamo se le classi "conto-corrente-dto.ts" e "lista-conti-corrente-dto.ts" vanno create dentro il componente "cc" (ContoCorrente) o direttamente su "app"

**Comment by luca-lezzerini** [comment]
Create una cartella dto e metteteli lì dentro, sul client, dentro app

**Comment by MatteoPalombo99** [comment]
Ricevuto
