### ISSUE TITLE
dubbi su dove richiamare i servizi creati

### ISSUE THREAD

**Issue by marcobonaccorso** [luca-lezzerini/conto-corrente-bancario-s#45]
Nel ticket " Dubbi nella gestione dei serviceImpl #42 " abbiamo chiesto approfondimenti sulla gestione dei service impl ma non sappiamo dove richiamare i servizi creati. Che controller vanno creati?

**Comment by luca-lezzerini** [comment]
Creerò un gruppo SystemAdmin. Mentre aggiorno UML procede pure con SystemAdminController e Service/Impl.
Non chiudete questo ticket che lo chiudo io appena aggiornato UML

**Comment by luca-lezzerini** [comment]
Risolto 7f572785b5fe570a2bdf1ad31a244ca0509a8ae0
