### ISSUE TITLE
Aggiungere pulsante home su tutte le pagine

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/conto-corrente-bancario-s#47]
Tutte le pagine devono avere in alto a sinistra un pulsante di ritorno alla home.
Metterlo in app.component in modo che sia presente su tutte le pagine.
Non duplicare il codice mettendo un bottone per ogni pagina

**Comment by ValeriaCom** [comment]
Prof, quando vado a iniettare il router nel metodo tornaHome() che ho inserito nell'app components principale è come se non lo vedesse.
Cosa sto sbagliando? 
Allego foto :

![CatturaRouter](https://user-images.githubusercontent.com/78487304/111051533-0ae79300-8454-11eb-9279-7f1f026d7c97.PNG)

**Comment by ValeriaCom** [comment]
risolto al commit cf60d2021fe4482a1dd79d3796e183be21abdffd
