### ISSUE TITLE
AccountManagementController è occupato?

### ISSUE THREAD

**Issue by MatteoPalombo99** [luca-lezzerini/conto-corrente-bancario-s#48]
Dobbiamo modificare AccountManagementController, possiamo?

**Comment by daniele-bit** [comment]
Potete modificare AccauntManagementController, prima del commit e una volta effettato il commit informatemi così chiudo questo ticket

**Comment by MatteoPalombo99** [comment]
```
@RequestMapping("/aggiungi-cc")
    @ResponseBody
    public ListaContiCorrenteDto aggiungiCc(@RequestBody ContoCorrenteDto dto) {
        //return accountManagementService.aggiungiCc(dto.getContoCorrente());
        throw new UnsupportedOperationException();
    }
```
Abbiamo aggiunto queste righe di codice, c'è bisogno di lavorare sul relativo service e serviceimpl. Il codice continua a compilare, posso committare?

**Comment by daniele-bit** [comment]
si, datemi poi la conferma dell'avvenuto commit

**Comment by MatteoPalombo99** [comment]
Commit effettuato  108a40ae87f8497907f2bf00425344f33067bd6e

**Comment by MatteoPalombo99** [comment]
Possiamo lavorare su AccountManagementService e AccountManagementServiceImpl?
O sono occupati?

**Comment by daniele-bit** [comment]
Potete lavorare, la prossima volta facciamo un ticket differente, che vorrei chiuderli una volta che mi avete fatto il commit.
il prossimo ticket  (dell'avvenuta lavorazione) crealo nuovo e assegnalo di nuovo a me, questo ora lo chiudo
