### ISSUE TITLE
L'ordine dei deleteAllInBatch va cambiato

### ISSUE THREAD

**Issue by MatteoPalombo99** [luca-lezzerini/conto-corrente-bancario-s#50]
L'ordine dei deleteAllInBatch va cambiato poichè esistono dei vincoli di integrità che non vengono rispettati nell'ordine attuale

**Comment by marcobonaccorso** [comment]
in questo momento sono così: 
  clienteRepository.deleteAllInBatch();
        contoCorrenteRepository.deleteAllInBatch();
        contoDepositoRepository.deleteAllInBatch();
        contoPrestitoRepsitory.deleteAllInBatch();

Come li vuoi?

**Comment by marcobonaccorso** [comment]
risolto al commit 73f73d4a228c40d6e3cca66721d7aef703530bea
