### ISSUE TITLE
Dobbiamo lavorare su AccountManagementService e AccountManagementServiceImpl

### ISSUE THREAD

**Issue by MatteoPalombo99** [luca-lezzerini/conto-corrente-bancario-s#52]
Possiamo lavorare su AccountManagementService e AccountManagementServiceImpl?
O sono occupati?

**Comment by daniele-bit** [comment]
Potete lavorare

**Comment by MatteoPalombo99** [comment]
Abbiamo concluso il lavoro che dovevamo fare, possiamo procedere al commit?

**Comment by daniele-bit** [comment]
Potete Committare

**Comment by MatteoPalombo99** [comment]
Commit eseguito 81066f9d4d85cb0ade074bf1e4cab614f4a7048a
