### ISSUE TITLE
autorizzazione Rotte

### ISSUE THREAD

**Issue by ValeriaCom** [luca-lezzerini/conto-corrente-bancario-s#53]
Ciao Daniele, abbiamo creato le rotte ma al momento vanno in conflitto sull'app-routing.module.ts.
Chi è che lo sta modificando?

**Comment by daniele-bit** [comment]
il mio gruppo ha effettuato una modifica, abbiamo dimenticato di avvisarvi .
Ci scusiamo per l'equivoco, sappiamo che è di vostra competenza, in quel momento avevamo il professore addosso e presi dal risolvere in fretta il problema non siamo riusciti ad avvisarvi (a causa della pressione).
di nuovo scusateci, se avete bisogno possiamo venire a darvi supporto.

**Comment by ValeriaCom** [comment]
ok grazie
