### ISSUE TITLE
UC Gestione CD

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/conto-corrente-bancario-s#6]

**Comment by nicoloabatecola** [comment]
Inserita funzionalità aggiungi al commit abb3e1a078dc29b25ffdea02771907fae07322f8.
Risolti merge e finalizzato inserimento al commit c063b6a2f4815fd3822708d61cb4cb601aa0cc5e

**Comment by matteo2025** [comment]
implementata cancellazione al commit 77cccc15ae42c7536dee033f8b8a30475930eab0

**Comment by matteo2025** [comment]
implementato metodo aggiorna al commit: 3240a28169985eeee5616f854276e32b1640b618

**Comment by matteo2025** [comment]
implementata modifica al commit: 638ddbe65da627f1ee35a72fe6b8c5c5858abeff
