### ISSUE TITLE
Possiamo modificare l'appmodule.ts per aggiungere ReactiveFormsModule?

### ISSUE THREAD

**Issue by MatteoPalombo99** [luca-lezzerini/conto-corrente-bancario-s#62]
Possiamo modificare l'appmodule.ts per aggiungere ReactiveFormsModule per procedere con lo sviluppo della combobox?

**Comment by daniele-bit** [comment]
si, potete procedere

**Comment by Emanuele1927** [comment]
Risolto al commit aa04f4b9db9277a38deebf4eb7d28a431ec2efcd

**Comment by daniele-bit** [comment]
informatemi una volta terminata la modifica così da poter chiudere questo ticket

**Comment by MatteoPalombo99** [comment]
Questo ticket può essere chiuso
