### ISSUE TITLE
UC Gestione conto prestito non riempie tabella all'avvio

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/conto-corrente-bancario-s#63]
Quando si entra dalla home sulla pagina Gestione Conto prestito, compare sempre il pulsante new ma non viene visualizzata la tabella con i dati già esistenti.
![image](https://user-images.githubusercontent.com/47611629/111137936-ab86a180-857f-11eb-953f-b51f78732e61.png)

Comportamento corretto: new viene mostrato solo se non ci sono record, altrimenti mostra il campo di testo, il pulsante aggingi e la tabella popolata con i conti disponibili sul DB

**Comment by MatteoPalombo99** [comment]
Risolto al commit 4cbbb3d094a50e017754f482eb9c53b51dbc9e9c
