### ISSUE TITLE
UC Gestione conto deposito

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/conto-corrente-bancario-s#64]
Il pulsante new si deve chiamare New e non Nuovo, e deve apparire solo se non ci sono record. Se cliccato apre la visualizzazione con aggiungi e il campo di input.
Se ci sono record si passa direttamente alla visualizzazione con il campo di input e aggiungi, con la tabella con i dati già presenti sul DB

**Comment by capponiFelice92** [comment]
1ff1925113d93e2638ca8a9f381b779d80fce653

**Comment by capponiFelice92** [comment]
completato al commit 1325aa799a2b4f39e1520b7daa8b9565d4052c9e

**Comment by capponiFelice92** [comment]
d9f4047b110ba52df42a18177169c123959767bf
con questo commit se cancello tutti i record si rivisualizza solo new.

**Comment by luca-lezzerini** [comment]
Non va bene. Se cancello tutti i record non mi compare new ma Associa con campo vuoto. New appare se rientro da home.

**Comment by capponiFelice92** [comment]
intende dire aggiungi o proprio associa?
