### ISSUE TITLE
Placeholder errati in Associa CC, CP e CD

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/conto-corrente-bancario-s#65]
I placeholder non devono essere scritti in cammellato ma come testo normale, in quanto destinati alla lettura da parte dell'utente.

**Comment by ValeriaCom** [comment]
risolto al commit 8bcff70eb225ab3a3a5b3ebb1baf733375a2335b

**Comment by luca-lezzerini** [comment]
Associa CC, CP e CD ancora hanno placeholder ricerca conto errato.

![image](https://user-images.githubusercontent.com/47611629/111143291-e7246a00-8585-11eb-8f79-a43cdf1787ac.png)

**Comment by ValeriaCom** [comment]
risolto al commit 8bcff70
