### ISSUE TITLE
(UC Movimenta CP #14) 

### ISSUE THREAD

**Issue by capponiFelice92** [luca-lezzerini/conto-corrente-bancario-s#88]
come da documentazione p65 cambiando il conto selezionato (ma anche selezionandolo la prima volta) la tabella che visualizza i movimenti viene aggiornata con la lista movimenti relativa a quel conto.

**Comment by capponiFelice92** [comment]
1) nel metodo cercaContoPrestito() (o simile) cambiare dto risposta, deve contenere anche la lista movimenti (associati al conto cercato), quando ritorna.

**Comment by nicoloabatecola** [comment]
Risolto prima parte al commit : 935c402cd8826ef3464fa440460434582e8b504d

**Comment by nicoloabatecola** [comment]
Risolto e funzionante al commit: 7067a139ae80dae15c2967e2cf9f8b51fb6cbdbf
